### ISSUE TITLE
What pages are we keeping / removing?

### ISSUE THREAD

**Issue by kmccloskey** [gregoryjpark/recycling#17]
I'm available all weekend if anything needs to be done if this doesn't work on your resolutions.  Just let me know if anything needs to be done or if you guys are busy i'll get done whatever needs to get done.

**Comment by gregoryjpark** [comment]
I vote to remove About Us (about.html). We need to have an index.html in our project, and we can continue calling that Home in the navbar.

**Comment by kmccloskey** [comment]
Sounds good to me

**Comment by onejesus** [comment]
Yeah lets just delete the about us page!
