### ISSUE TITLE
Add content to index.html

### ISSUE THREAD

**Issue by gregoryjpark** [gregoryjpark/recycling#22]
We need to have something in the content area / `<article>` on index.html. 

Since the why.html already has the 'why?'/motivation angle, the content on index.html could just be about the organization itself (maybe call it 'RecycleStuff'?)... e.g., Founding date, names of the org's leaders, mission statement, location of headquarters. 

Intersperse these bits/facts with nice recycling pictures.

**Comment by gregoryjpark** [comment]
@kmccloskey I assigned this to you but let me know if you'd rather do something else. No preference.

**Comment by kmccloskey** [comment]
This is done and pushed to don't break with the donation page as well.  Will be on all day tomorrow would like to discuss formatting.
